### ISSUE TITLE
Can't show all position of match letters

### ISSUE THREAD

**Issue by whcn** [tranhl/find-then-jump#30]
For example, there are many character 'a' and I want to jump to one of them. But sometime the plugin only show a part of match letters position when I invoke findThenJump.initiate.

**Comment by tranhl** [comment]
That is how the extension works at the current stage. Because all of your interaction with the extension happens within a text box, search input and letter choices are derived from the same search string. This means that in order for the extension to distinguish between search input and selecting a jump position, we need some sort of guarantee that the next letter is either a search input, or a jump position, and not both. To do this, the extension grabs the next few letters after each jump position and blacklists them, to prevent collisions when you type out a search input. This rapidly exhausts all the possible characters usable for jumping.

The easiest workaround is to simply type another character, that should narrow down the options enough that your intended jump position comes up as an option. Hope that explains things.

**Comment by whcn** [comment]
Thanks for your reply! It works.
